server:
  port: 8089
  servlet:
    context-path: /api/profile
management:
  server:
    port: 8189
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: secretpassword
  liquibase:
    default-schema: profile
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: profile-app
  jpa:
    hibernate:
      ddlAuto: create
    show-sql: false
    open-in-view: false
eureka:
    client:
      service-url:
        defaultZone=http://localhost:8761/eureka/: