server:
  port: 8091
  servlet:
    context-path: /api/public-info
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: password
  liquibase:
    default-schema: public_bank_information
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: public-info-app
  jpa:
   hibernate:
    ddl-auto: update
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
#    lease-renewal-interval-in-seconds: 30
#    properties:
#      hibernate:
#        default_schema: public_bank_information
